### ISSUE TITLE
Security Exception in initial root/root login

### ISSUE THREAD

**Issue by jslootweg** [polterguy/magic#26]
I see the exception below in the console, the Setup page detail won't save either

`info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\jslootweg\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
Hosting environment: Development
Content root path: C:\Work\magic\magic.backend
Now listening on: http://localhost:63247
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:63247/
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'magic.endpoint.controller.EndpointController.Get (magic.endpoint.controller)'
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "Get", controller = "Endpoint"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.ActionResult] Get(System.String) on controller magic.endpoint.controller.EndpointController (magic.endpoint.controller).
info: Microsoft.AspNetCore.Mvc.StatusCodeResult[1]
      Executing HttpStatusCodeResult, setting HTTP status code 404
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action magic.endpoint.controller.EndpointController.Get (magic.endpoint.controller) in 55.1595ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'magic.endpoint.controller.EndpointController.Get (magic.endpoint.controller)'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 209.46720000000002ms 404 text/html
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:63247/magic/modules/system/ping
info: Microsoft.AspNetCore.Cors.Infrastructure.CorsService[4]
      CORS policy execution successful.
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'magic.endpoint.controller.EndpointController.Get (magic.endpoint.controller)'
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "Get", controller = "Endpoint"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.ActionResult] Get(System.String) on controller magic.endpoint.controller.EndpointController (magic.endpoint.controller).
info: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
      Executing ObjectResult, writing value of type 'Newtonsoft.Json.Linq.JObject'.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action magic.endpoint.controller.EndpointController.Get (magic.endpoint.controller) in 82.8117ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'magic.endpoint.controller.EndpointController.Get (magic.endpoint.controller)'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 96.7008ms 200 application/json; charset=utf-8
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:63247/magic/modules/system/auth/authenticate?username=root&password=root
info: Microsoft.AspNetCore.Cors.Infrastructure.CorsService[4]
      CORS policy execution successful.
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'magic.endpoint.controller.EndpointController.Get (magic.endpoint.controller)'
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "Get", controller = "Endpoint"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.ActionResult] Get(System.String) on controller magic.endpoint.controller.EndpointController (magic.endpoint.controller).
info: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
      Executing ObjectResult, writing value of type 'Newtonsoft.Json.Linq.JObject'.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action magic.endpoint.controller.EndpointController.Get (magic.endpoint.controller) in 78.664ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'magic.endpoint.controller.EndpointController.Get (magic.endpoint.controller)'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 94.4521ms 200 application/json; charset=utf-8
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:63247/magic/modules/system/setup/load-config-file
info: Microsoft.AspNetCore.Cors.Infrastructure.CorsService[4]
      CORS policy execution successful.
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'magic.endpoint.controller.EndpointController.Get (magic.endpoint.controller)'
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "Get", controller = "Endpoint"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.ActionResult] Get(System.String) on controller magic.endpoint.controller.EndpointController (magic.endpoint.controller).
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action magic.endpoint.controller.EndpointController.Get (magic.endpoint.controller) in 10.4389ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'magic.endpoint.controller.EndpointController.Get (magic.endpoint.controller)'
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.Security.SecurityException: Access denied
   at magic.lambda.auth.helpers.TicketFactory.VerifyTicket(ITicketProvider ticketProvider, String roles)
   at magic.lambda.auth.VerifyTicket.Signal(ISignaler signaler, Node input)
   at magic.signals.services.Signaler.Signal(String name, Node input)
   at magic.lambda.Eval.ExecuteAsync(ISignaler signaler, IEnumerable`1 nodes)
   at magic.lambda.Eval.SignalAsync(ISignaler signaler, Node input)
   at magic.signals.services.Signaler.SignalAsync(String name, Node input)
   at magic.endpoint.services.ExecutorAsync.<>c__DisplayClass8_0.<<ExecuteUrl>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at magic.signals.services.Signaler.ScopeAsync(String name, Object value, Func`1 functor)
   at magic.endpoint.services.ExecutorAsync.<>c__DisplayClass8_0.<<ExecuteUrl>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at magic.signals.services.Signaler.ScopeAsync(String name, Object value, Func`1 functor)
   at magic.endpoint.services.ExecutorAsync.ExecuteUrl(String url, String verb, IEnumerable`1 args, JContainer payload)
   at magic.endpoint.services.ExecutorAsync.ExecuteGetAsync(String url, DateTime ifModifiedSince, IEnumerable`1 args)
   at magic.endpoint.controller.EndpointController.Get(String url)
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 102.3743ms 500 application/json
`

**Comment by polterguy** [comment]
Hmm, there are a couple of things which I can see immediately that are _"weird"_. First, it seems to be using a non-standard port, which makes me think you might have edited the _"launchSettings.json"_ file. I have included below how it looks like in the GIT repo.

The other thing I see that is weird, is that it's trying to access your data key repository, which doesn't make sense to me. Have you reconfigured parts of the default download for some reasons? And if you have, does it work _"out of the box"_ ...?

If neither of these answers your questions, I'd love to know a couple of things.

1. Version of .Net Core - Magic requires .Net Core 3.0 installed. I know for a fact that it does not work in Visual Studio 2017 on my PC workstation for instance, due to this.
2. Are you using Visual Studio or the `dotnet run` command through some command line interface (e.g. terminal window in VS Code?)
3. Is this on a development machine, or a server? As in, do you run Kestrel directly, or have you created some sort of tunnel/gateway through IIS, Apache or Nginx, etc ...?
4. Have you done any other modifications to the system in any ways ...? (Adding C# controllers, other NuGet packages, etc ...?)

On a _"normal default"_ Windows development machine, things should work. I did however blunder earlier today, and released a new version of _"magic.library"_. Make sure you are using the latest version of this NuGet package ...

```json
{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:55247/",
      "sslPort": 0
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "launchUrl": "magic/modules/system/ping",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "magic.backend": {
      "commandName": "Project",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "applicationUrl": "http://localhost:55247/"
    }
  }
}
```

**Comment by polterguy** [comment]
Let me know if this one got solved or not, or if I have to dig deeper. You can just close it if you're OK ...

**Comment by polterguy** [comment]
OK, I'm going to close this one - Feel free to re-open it, and provide more information if you're still struggling ...
